"""create insights table

Revision ID: ff64484bd130
Revises: ee363a552c66
Create Date: 2026-06-27 18:27:18.112930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff64484bd130'
down_revision: Union[str, None] = 'ee363a552c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment', native_enum=False), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('success', 'fallback', name='insightstatus', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_interaction_id'), 'insights', ['interaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_interaction_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
